# 1 自己实现LinearRegression
# 2 使用sklearn中的LinearRegression
# 3 用KNN算法进行回归

In [1]:


from sklearn.datasets import load_boston
import numpy as np
import matplotlib.pyplot as plt
from LinearRegression import LinearRegression
from model_selection import train_test_split 

### 加载数据

In [2]:
data = load_boston()
data_X = data.data
data_y = data.target

In [3]:
data_X.shape

(506, 13)

In [4]:
data_y.shape

(506,)

### 去除边界数据

In [5]:
data_X = data_X[data_y<50]

In [6]:
data_y = data_y[data_y<50]

### 分割数据

In [7]:
X_train,y_train,X_test,y_test = train_test_split(data_X,data_y,seed=666)

### 训练模型

In [8]:
LR = LinearRegression()
LR.fit_normal(X_train,y_train)

LinearRegression()

In [43]:
LR.predict(X_test)

array([ 18.08047724,  25.52374702,  12.93068154,  32.89616169,
        24.17956679,   2.67010028,  26.64700396,  32.23851244,
        13.96168643,  24.04280799,  14.93247906,  10.58513734,
        30.28710828,  16.2782111 ,  23.67817017,  25.64047759,
        18.67821777,  24.02076592,  28.77437534,  26.93946254,
        12.81354434,  27.22770353,  26.0804716 ,  23.41900039,
        20.79727917,  31.96786535,  14.90862058,  20.954883  ,
        12.92314457,  29.80207127,  35.28684545,   5.03624207,
        13.10143242,  35.54317123,  15.98890703,  21.53597166,
        12.47621364,  29.12864349,  27.36022467,  24.05031901,
        14.35220626,  23.61433371,  10.90347719,  22.38154099,
        18.62937294,  16.37126778,  24.43078261,  33.06293684,
        19.19809767,  27.04404675,  18.05674457,  14.85136715,
        25.08935314,  16.0884098 ,  21.74619772,  16.3194766 ,
        24.25591698,  11.72935395,  27.92260116,  31.05867941,
        20.17444189,  24.9964365 ,  25.99734127,  12.14

In [9]:
LR.score(X_test,y_test)

0.81298026026583592

In [10]:
LR.cofficients_

array([ -1.18919477e-01,   3.63991462e-02,  -3.56494193e-02,
         5.66737830e-02,  -1.16195486e+01,   3.42022185e+00,
        -2.31470282e-02,  -1.19509560e+00,   2.59339091e-01,
        -1.40112724e-02,  -8.36521175e-01,   7.92283639e-03,
        -3.81966137e-01])

In [11]:
LR.intercept_

array([ 34.1614355])

## 使用sklearn重封装好的LinearRegression(使用正规方差计算的score不收到特征之间的规模不同的影响)
是否归一化 对结果没有影响

In [12]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [13]:
data = load_boston()
data_X = data.data
data_y = data.target
data_X = data_X[data_y<50.0]
data_y = data_y[data_y<50.0]

In [14]:
#X_train,X_test,y_train,y_test = train_test_split(data_X,data_y,random_state = 666,test_size = 0.2)
#若全部使用sklearn中的方法我们应该使用sklearn中的split 
#    但是为了方便和上面自己实现的方法进行对比  我们依然使用自己的train_test_split切割完毕的数据


In [15]:
sklearn_LR = LinearRegression()

In [16]:
sklearn_LR.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [17]:
sklearn_LR.coef_

array([ -1.18919477e-01,   3.63991462e-02,  -3.56494193e-02,
         5.66737830e-02,  -1.16195486e+01,   3.42022185e+00,
        -2.31470282e-02,  -1.19509560e+00,   2.59339091e-01,
        -1.40112724e-02,  -8.36521175e-01,   7.92283639e-03,
        -3.81966137e-01])

In [18]:
sklearn_LR.intercept_

34.161435496245851

In [19]:
sklearn_LR.score(X_test,y_test)

0.81298026026584858

## 二、KNN Regressor

### 数据归一化

In [20]:
from sklearn.preprocessing import StandardScaler
sS = StandardScaler()
sS.fit(X_train)
sS_X_train = sS.transform(X_train)
sS_X_test = sS.transform(X_test)

In [21]:
from sklearn.neighbors import KNeighborsRegressor

### 分类器使用默认参数！

In [22]:
KNR = KNeighborsRegressor()

In [23]:
KNR_NO = KNeighborsRegressor()

#### 未使用数据归一化！

In [24]:
KNR_NO.fit(X_train,y_train)

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
          metric_params=None, n_jobs=1, n_neighbors=5, p=2,
          weights='uniform')

In [25]:
KNR_NO.score(X_test,y_test)

0.58654121983008989

#### 使用了数据归一化！

In [26]:
KNR.fit(sS_X_train,y_train)

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
          metric_params=None, n_jobs=1, n_neighbors=5, p=2,
          weights='uniform')

In [27]:
KNR.score(sS_X_test,y_test) #此分数 是彼分数  计算标准一样！

0.84664511530389497

In [28]:
y_p = KNR.predict(sS_X_test)

In [29]:
from metrics import r2_score
r2_score(y_test,y_p)

0.84664511530389508

### 使用网格搜索选用最好的超参数

In [30]:
from sklearn.model_selection import GridSearchCV

In [31]:
para_grid = [
    {
        "n_neighbors":[i for i in range(1,11)],
        "weights":["uniform"]
    },
    {
        "n_neighbors":[i for i in range(1,11)],
        "weights":["distance"],
        "p":[i for i in range(1,6)]
    }
]

In [32]:
grid_search = GridSearchCV(KNR,param_grid=para_grid,n_jobs=1,verbose=2)

In [33]:
grid_search.fit(sS_X_train,y_train)

Fitting 3 folds for each of 60 candidates, totalling 180 fits
[CV] n_neighbors=1, weights=uniform ..................................
[CV] ................... n_neighbors=1, weights=uniform, total=   0.0s
[CV] n_neighbors=1, weights=uniform ..................................
[CV] ................... n_neighbors=1, weights=uniform, total=   0.0s
[CV] n_neighbors=1, weights=uniform ..................................
[CV] ................... n_neighbors=1, weights=uniform, total=   0.0s
[CV] n_neighbors=2, weights=uniform ..................................
[CV] ................... n_neighbors=2, weights=uniform, total=   0.0s
[CV] n_neighbors=2, weights=uniform ..................................
[CV] ................... n_neighbors=2, weights=uniform, total=   0.0s
[CV] n_neighbors=2, weights=uniform ..................................
[CV] ................... n_neighbors=2, weights=uniform, total=   0.0s
[CV] n_neighbors=3, weights=uniform ..................................
[CV] ..........

[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s


[CV] ................... n_neighbors=7, weights=uniform, total=   0.0s
[CV] n_neighbors=7, weights=uniform ..................................
[CV] ................... n_neighbors=7, weights=uniform, total=   0.0s
[CV] n_neighbors=8, weights=uniform ..................................
[CV] ................... n_neighbors=8, weights=uniform, total=   0.0s
[CV] n_neighbors=8, weights=uniform ..................................
[CV] ................... n_neighbors=8, weights=uniform, total=   0.0s
[CV] n_neighbors=8, weights=uniform ..................................
[CV] ................... n_neighbors=8, weights=uniform, total=   0.0s
[CV] n_neighbors=9, weights=uniform ..................................
[CV] ................... n_neighbors=9, weights=uniform, total=   0.0s
[CV] n_neighbors=9, weights=uniform ..................................
[CV] ................... n_neighbors=9, weights=uniform, total=   0.0s
[CV] n_neighbors=9, weights=uniform ..................................
[CV] .

[CV] ............. n_neighbors=4, p=3, weights=distance, total=   0.0s
[CV] n_neighbors=4, p=3, weights=distance ............................
[CV] ............. n_neighbors=4, p=3, weights=distance, total=   0.0s
[CV] n_neighbors=4, p=4, weights=distance ............................
[CV] ............. n_neighbors=4, p=4, weights=distance, total=   0.0s
[CV] n_neighbors=4, p=4, weights=distance ............................
[CV] ............. n_neighbors=4, p=4, weights=distance, total=   0.0s
[CV] n_neighbors=4, p=4, weights=distance ............................
[CV] ............. n_neighbors=4, p=4, weights=distance, total=   0.0s
[CV] n_neighbors=4, p=5, weights=distance ............................
[CV] ............. n_neighbors=4, p=5, weights=distance, total=   0.0s
[CV] n_neighbors=4, p=5, weights=distance ............................
[CV] ............. n_neighbors=4, p=5, weights=distance, total=   0.0s
[CV] n_neighbors=4, p=5, weights=distance ............................
[CV] .

[CV] ............. n_neighbors=8, p=3, weights=distance, total=   0.0s
[CV] n_neighbors=8, p=4, weights=distance ............................
[CV] ............. n_neighbors=8, p=4, weights=distance, total=   0.0s
[CV] n_neighbors=8, p=4, weights=distance ............................
[CV] ............. n_neighbors=8, p=4, weights=distance, total=   0.0s
[CV] n_neighbors=8, p=4, weights=distance ............................
[CV] ............. n_neighbors=8, p=4, weights=distance, total=   0.0s
[CV] n_neighbors=8, p=5, weights=distance ............................
[CV] ............. n_neighbors=8, p=5, weights=distance, total=   0.0s
[CV] n_neighbors=8, p=5, weights=distance ............................
[CV] ............. n_neighbors=8, p=5, weights=distance, total=   0.0s
[CV] n_neighbors=8, p=5, weights=distance ............................
[CV] ............. n_neighbors=8, p=5, weights=distance, total=   0.0s
[CV] n_neighbors=9, p=1, weights=distance ............................
[CV] .

[Parallel(n_jobs=1)]: Done 180 out of 180 | elapsed:    5.0s finished


GridSearchCV(cv=None, error_score='raise',
       estimator=KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
          metric_params=None, n_jobs=1, n_neighbors=5, p=2,
          weights='uniform'),
       fit_params=None, iid=True, n_jobs=1,
       param_grid=[{'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 'weights': ['uniform']}, {'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 'weights': ['distance'], 'p': [1, 2, 3, 4, 5]}],
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=2)

In [34]:
grid_search.best_params_

{'n_neighbors': 5, 'p': 1, 'weights': 'distance'}

### 分类器使用了网格搜索后的最佳参数并进行了数据归一化处理

In [35]:
grid_search.best_estimator_.score(sS_X_test,y_test)

0.88099665099417701

### 经过对比 KNN 即使选择了最优的参数后 回归的效果依旧一般
不过gridsearch ~~计算score的方法和我们的不一样！！！！ 这点我们需要注意
不同的评价标准不好比较啊~~
### 但是我想到了 数据归一化对KNN的影响是很大的！！！
所以归一化了数据 模型的score得到了 非常大的提升 ？ ~~但是标标准不一样 依旧不好比较~~
### 经过我的探索与创造  我发现他们的Score计算方法居然是一样的！


## 3 线性回归对数据具有可解释性

In [36]:
arg_index = sklearn_LR.coef_.argsort()

In [37]:
data.feature_names[arg_index]

array(['NOX', 'DIS', 'PTRATIO', 'LSTAT', 'CRIM', 'INDUS', 'AGE', 'TAX',
       'B', 'ZN', 'CHAS', 'RAD', 'RM'],
      dtype='<U7')

In [38]:
print(data.DESCR)

Boston House Prices dataset

Notes
------
Data Set Characteristics:  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive
    
    :Median Value (attribute 14) is usually the target

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per $10,000
        - PTRATIO  pupil-teacher ratio by town
      

In [49]:
import numpy as np
xxx =np.array([[1,2,3],[4,5,6],[7,8,9]])

In [50]:
xxx.shape

(3, 3)

In [41]:
yyy = np.array([[1],[2],[3]])

In [51]:
yyy.shape

(3, 1)

In [42]:
xxx.dot(yyy)

array([[14],
       [32]])

In [44]:
nnn = np.array([1,2,3])

In [52]:
yyy = np.array([1,2,3])

In [46]:
yyy  - nnn

array([[ 0, -1, -2],
       [ 1,  0, -1],
       [ 2,  1,  0]])

In [48]:
def dJ(theta, X_b, y):
    return X_b.T.dot(X_b.dot(theta) - y) * 2. / len(y)

In [53]:
theta = np.array([3,2,1])

In [54]:
dJ(theta,xxx,yyy)

array([ 276.,  328.,  380.])

In [56]:
xxx.dot(theta)

array([10, 28, 46])

In [57]:
xxx.shape

(3, 3)

In [58]:
theta.shape

(3,)

### 矩阵.dot(向量) 会返回一个向量