# 评估一个算法

In [1]:
import numpy as np
from sklearn.datasets import load_iris

### 将数据集划分为测试集和训练集

In [2]:
iris=load_iris()

In [3]:
iris.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names'])

### 要划分的数据集

In [4]:
iris.data

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2],
       [ 5.4,  3.9,  1.7,  0.4],
       [ 4.6,  3.4,  1.4,  0.3],
       [ 5. ,  3.4,  1.5,  0.2],
       [ 4.4,  2.9,  1.4,  0.2],
       [ 4.9,  3.1,  1.5,  0.1],
       [ 5.4,  3.7,  1.5,  0.2],
       [ 4.8,  3.4,  1.6,  0.2],
       [ 4.8,  3. ,  1.4,  0.1],
       [ 4.3,  3. ,  1.1,  0.1],
       [ 5.8,  4. ,  1.2,  0.2],
       [ 5.7,  4.4,  1.5,  0.4],
       [ 5.4,  3.9,  1.3,  0.4],
       [ 5.1,  3.5,  1.4,  0.3],
       [ 5.7,  3.8,  1.7,  0.3],
       [ 5.1,  3.8,  1.5,  0.3],
       [ 5.4,  3.4,  1.7,  0.2],
       [ 5.1,  3.7,  1.5,  0.4],
       [ 4.6,  3.6,  1. ,  0.2],
       [ 5.1,  3.3,  1.7,  0.5],
       [ 4.8,  3.4,  1.9,  0.2],
       [ 5. ,  3. ,  1.6,  0.2],
       [ 5. ,  3.4,  1.6,  0.4],
       [ 5.2,  3.5,  1.5,  0.2],
       [ 5.2,  3.4,  1.4,  0.2],
       [ 4.7,  3.2,  1.6,  0.2],
       [ 4

In [5]:
rate = 0.2
data_len = len(iris.data)

In [6]:
data_len

150

### 数据集！！！！

In [7]:
x_data=iris.data
y_data=iris.target

## 划分数据集
### 划分数据集方法1

In [9]:
random_index=np.random.permutation(data_len)
test_num = int(rate*data_len)
random_index
x_test = x_data[random_index[:test_num]]
y_test = y_data[random_index[:test_num]]
x_train = x_data[random_index[test_num:]]
y_train = y_data[random_index[test_num:]]

In [10]:
x_train.shape
y_train.shape

(120,)

### 划分数据集方法2

In [47]:
%run my_train_test_split.py

In [48]:
 x_train,y_train,x_test,y_test = train_test_split(x_data,y_data)

### 划分数据集方法3

In [86]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x_data,y_data)

## 1.使用自己的分类器训练

In [49]:
from my_knn_classifier import my_knn_classifier

In [50]:
mc = my_knn_classifier(6)

In [51]:
mc.fit(x_train,y_train)

In [52]:
y_predict=mc.predict_Y(x_test)
y_predict

array([0, 1, 1, 2, 2, 0, 0, 0, 1, 1, 2, 0, 0, 2, 1, 0, 1, 2, 0, 1, 0, 2, 2,
       2, 2, 2, 2, 1, 1, 1])

In [53]:
y_test

array([0, 1, 1, 2, 2, 0, 0, 0, 1, 1, 2, 0, 0, 2, 1, 0, 1, 2, 0, 1, 0, 2, 2,
       2, 2, 2, 2, 2, 1, 1])

In [54]:
corrcet=np.sum(y_predict==y_test)


In [55]:
mc.score(x_test,y_test)

0.96666666666666667

## 2.使用sklearn中的模型训练

In [65]:
from sklearn.neighbors import KNeighborsClassifier
knnclassifier = KNeighborsClassifier(6)
knnclassifier.fit(x_train,y_train)
sk_predict = knnclassifier.predict(x_test)
sk_correct = np.sum(sk_predict==y_test)

## 计算准确率

In [66]:
accuracy = corrcet/len(y_test)
accuracy

0.96666666666666667

In [67]:
sk_accuracy=sk_correct/len(y_test)
sk_accuracy

0.96666666666666667

### 自己写的计算accuracy的函数

In [83]:
from metrics import accuracy_calculate
accuracy_calculate(y_test,sk_predict)

0.93333333333333335

### sklearn 中的计算accuracy的accuracy_score函数（传入真实结果，预测结果）

In [81]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,sk_predict)

0.93333333333333335

### sklearn classifier中的score

In [45]:
knnclassifier.score(x_test,y_test)

0.94736842105263153

## 二、sklearn的全流程

In [77]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
#划分数据集
x_train,x_test,y_train,y_test = train_test_split(x_data,y_data,test_size=0.3,random_state=66)
# 训练模型
knnclassifier = KNeighborsClassifier(6)
knnclassifier.fit(x_train,y_train)
#预测
sk_predict = knnclassifier.predict(x_test)
#准确率
knnclassifier.score(x_test,y_test)

0.93333333333333335